package misiek.example.spacetraveler
var listOfFunFacts = mutableListOf<String>(
    "If the Universe is infinite, there should be an infinite number of stars, which means day and night would be equally bright. This paradox, named after Heinrich Olbers, argues that the Universe cannot be infinite and static. Today we know that the visible Universe is finite (around 46 billion light years) since light from distant regions is yet to travel to Earth.",
    "The Universe is expanding in all directions, at a faster rate the farther away we look. In 1929, Hubble discovered that stars appear slightly redder than one would expect based on their spectra alone. Just as sound in the air has a lower pitch when the source is moving away from us, light emitted by distant galaxies becomes redder (shifts toward lower frequencies) as it travels away from the Earth. The lower the frequency of light, the less energy it carries. Because light from distant galaxies appears redshifted, the intensity that reaches us is lower; another argument that solves Olbers’ paradox.",
    "The Universe is expanding, so we naturally expect that it must have started at a single point of infinite density sometime in the past, which expanded suddenly in an event known as the Big Bang. This early explosion scattered a ball of glowing fire across the whole Universe, which we can observe today as Cosmic Background Radiation (CBR). It was discovered in 1964 by American astronomers Arno Penzias and Robert Wilson.",
    "Andromeda is the nearest major galaxy to the Milky Way, with a mass approximately twice that of our galaxy. As the name suggests, it is visible in the constellation of Andromeda around autumn and winter, appearing as a smudge of light larger than the full Moon. It has its own set of satellite galaxies, the largest of which are M32 and M110, both clearly visible with a pair of binoculars or a telescope.",
    "Andromeda is on a collision course with our galaxy. It is believed that they will merge to form an even bigger galaxy in around 4.5 billion years.  However, it is improbable that any given star or planet will individually collide, as the space between them is immense. Such collisions are relatively common in the Universe. Indeed, several dwarf galaxies, such as the Sagittarius Dwarf Spheroidal Galaxy (Sgr dSph), are already in the process of merging with the Milky Way.",
    "Stars at the edge of our galaxy move faster than we predict based on the distribution of visible matter in our galaxy. The simplest way to resolve this discrepancy is to postulate the existence of non-luminous matter, which we call dark matter.",
    "Every star emits light according to the so-called black body distribution law. The wavelength at which this distribution peaks depends on the star’s surface temperature, and it is related to the wavelength of maximum emission through Wien’s Law. Since the Sun has a surface temperature of 5778K, its wavelength of maximum emission is at 500nm, corresponding to a green color. However, when the human eye factors in the other colors around the peak, and because shorter wavelengths (like blue and green) are scattered more by the Earth’s atmosphere, the Sun appears to be a yellowish-white color.",
    "Without the Moon stabilizing Earth’s rotational axis, the Earth tilt could vary as much as 85 degrees. In this case, the Sun could move from directly over the equator to directly over the poles in just a few million years. This would result in dramatic climatic shifts, potentially impacting the development of life. It is estimated that fewer than 10% of terrestrial planets have a satellite large enough to stabilize their rotational axis.",
    "Venus is the planet that comes closest to Earth during conjunction, but Mercury is closest to Earth, on average. In fact, because it is the planet with the smallest orbital radius, Mercury is also the nearest neighbor to every other planet in the Solar System.",
    "There is no sound in space since there is no medium (like the atmosphere on Earth) in which sound waves can propagate. However, this doesn’t mean that all space is completely silent. Sound can propagate on planets with a thin atmosphere, such as Mars, but it would probably sound slightly different from what you’re used to.",
    "According to the theory of relativity, a clock traveling close to the speed of light ticks slower than one at rest. Compared to stationary observers on Earth, passengers in a fast-moving spaceship would therefore advance further into the future in the same period of their own time. If a rocket were able to provide a constant 1g acceleration, it would be possible to travel through the entire visible Universe in just one lifetime",
    "To be precise, the Sun and the planets all orbit around their common center of mass. Of course, since the Sun contains around 99.8% of all matter in our solar system, the center of mass is not that far away from the center of the Sun itself. At most, it’s a few miles from its surface.",
    "Astronomers discover habitable planets by measuring their host star’s radial velocity as it moves around the barycenter of the system. If the system’s orbital plane coincides with our line of view, planets can transit on the disk of their host star, thereby causing a measurable dip in the luminosity. The Kepler Space Telescope, launched by NASA in 2009, constantly monitored the luminosity of approximately 150,000 stars, detecting more than 2,600 exoplanets during its lifetime.",
    "The Milky Way has about fifty satellite galaxies orbiting around it. Two of these are visible to the naked eye, the Big and Small Magellanic Clouds. The former is 1/100th of our galaxy’s size, but it lacks a clean spiral shape, probably because of the strong gravitational pull exerted by the Milky Way",
    "Just like planets are grouped in solar systems and stars are grouped in galaxies, so are galaxies grouped in clusters. Andromeda and the Milky Way are the largest galaxies in the Local Group, while the Triangulum Galaxy is the third largest by size. In turn, The Local Group belongs to the Virgo Supercluster, a massive collection of over 100 galaxy groups and clusters",
    "The theory of relativity postulates that no signal can travel faster than light. However, some theories suggest that this could be possible by contracting the space in front of a body while expanding the space behind it. Originally proposed by Mexican physicist Alcubierre, this mechanism requires negative energy density, i.e., negative mass. If exotic matter with these properties can be found, then faster-than-light-travel might indeed be possible.",
    "There is no air or atmosphere in space. Since it is a vacuum, sound waves will have no medium to travel to. That means, no one will hear you scream in space, even if you shout the loudest! While sound waves need a medium to travel, radio waves can travel in the void of space. Astronauts use radios to stay in communication while in space since radio waves can still be sent and received in a vacuum environment.",
    "The hottest planet in the solar system is Venus. This scorching planet has an average surface temperature of about 450 °C. Interestingly, Venus is not the closest planet to the Sun, Mercury is. Mercury has no atmosphere to regulate temperature so it has a very large temperature fluctuation. Venus, on the other hand, has the thickest atmosphere among all planets. This atmosphere traps heat, making Venus very hot.",
    "The sheer size of space makes it impossible to accurately predict just how many stars we have. Right now, scientists and astronomers use the number of stars only within our galaxy, the Milky Way, to estimate. That number is between 200-400 billion stars and there are estimated to be billions of galaxies so the stars in space really are completely uncountable.",
    "Neutron stars are the densest and tiniest stars in the known universe and although they only have a radius of about 10 km, they may have a mass of a few times that of the Sun. They can rotate up to 60 times per second after they are born from a core-collapse supernova star explosion and have been known to spin as fast as 600-712 times per second because of their physics.",
    "There may be a planet made out of diamonds. As space facts go, this is pretty impressive. Research by Yale University scientists suggests that a rocky planet called 55 Cancri e. It is twice the size of Earth and has a mass eight times greater. It may have a surface made up of graphite and diamond. It’s 40 light-years away but visible to the naked eye in the constellation of Cancer.",
    "The gas giant Jupiter is a failed star. Jupiter, the largest planet in the solar system, is composed of hydrogen and helium. These are the same elements that our Sun is made up of. However, Jupiter is not large enough to start nuclear fusion and generate its own energy. If it were around 80 times bigger, it would become a star with low mass.",
    "Enceladus, Saturn’s Moon, is the most reflective body in the solar system. Enceladus has an icy shell that reflects about 100% of the light that reaches it. It does not absorb much sunlight which makes it a very cold world with temperatures around -201 °C. This icy world spurts water jets which are thought to be from its internal global ocean. This moon is one of the strongest candidates for life outside Earth.",
    "The Sun will engulf Earth 5 billion years from now. The Sun is still a main-sequence star now. It generates energy by turning hydrogen into helium. As it turns into a red giant, it would become bigger and brighter. When our Sun reaches this stage, its expansion would likely reach the orbit of the red planet Mars. Though the Sun is not yet a red giant, it is still much bigger than the Earth. ",
    "In 3.75 billion years the Milky Way and Andromeda galaxies will collide.",
    "The largest known asteroid is 965 km wide.",
    "The temperature in the sun’s core is estimated to be 15 million degrees Celsius. The sun’s core generates energy through nuclear fusion, and this is when hydrogen is converted into helium. And since objects are prone to expanding when subjected to heat, the sun would explode were it not for its incredible gravitational pull.",
    "When you look at a star, what you actually see is how it was in the past.",
    " Most galaxies have a central black hole.",
    "All planets in the solar system have been visited by uncrewed spacecraft.",
    "There are no seasons in Jupiter like those experienced in other planets like Earth and Mars. This is due to the fact that the axis is only tilted by 3.13 degrees.",
    "The boundary of the solar system ends in a spherical cloud known as the Oort cloud.",
    "Jupiter’s core is huge and dense, although its composition is not completely substantiated. However, scientists believe that a layer of helium-rich fluid metallic hydrogen wraps around its core and the whole thing is then surrounded by a dense hydrogen atmosphere.",
    "Jupiter experiences damaging storms. The storms in Jupiter are rapidly moving and can grow to envelop a substantial area and cause incredible damage. The storms can grow to thousands of kilometers within a few hours.",
    "The sky is so dark on Pluto that a person would be able to see stars during the day.",
    "Small planets typically have solid nuclei. However, because of the presence of sulphur, mercury’s core is liquid",
    "About 1.4 billion years ago, a day on Earth was just 18 hours 41 minutes long.",
    "Jupiter’s atmospheric pressure is 100 times greater than Earth’s. That atmospheric pressure cannot sustain any life. Only Tardigrades can survive in that kind of atmospheric pressure",
    "Jupiter has a unique visible spot called the Great Red Spot. The Great Red Spot is a huge storm that rages since 300 years ago. Scientists say the spot is so enormous that 3 Earth’s could comfortably fit in it.",
    "The closest star system to us, Proxima Centauri, is 4.25 light-years away.",
    "Jupiter is one of the two gas giants in our solar system. It consists mainly of hydrogen (90%) and helium (10%).",
    "Jupiter’s magnetic field is very powerful. It’s believed to be 14 times more powerful that earth’s magnetic field.",
    "The largest moon in the solar system, called Ganymede, happens to be one of Jupiter’s moons. It’s, in fact, the largest of the Jupiter’s moons. Jupiter’s moons are also referred to as Jovian Satellites. The second and third largest of the Jupiter’s moons are Callisto and Lo respectively. Ganymede, which has a diameter of about 5, 268 kilometers, has even been proven to be larger than Mercury.",
    "Jupiter takes 11.86 Earth years to orbit the sun. This implies that when seen from Earth, Jupiter appears to move slowly. For Jupiter to move from one constellation to another, it takes many months.",
    "Jupiter experiences the shortest day than any planet in the solar system. It spins on its own axis once each 9 hours and 55 minutes. The fast rotation tends to flatten Jupiter a little bit, providing it an oblate shape.",
    "Jupiter is visibly the largest and most massive planet in the entire solar system. It has a total mass of 1.90 x 10^27 kg and an average diameter of 139,822 km.",
    "Some astronomers hypothesize that Pluto is just an escaped satellite of Neptune that pulled out of Neptune’s atmosphere and made its own orbit.",
    "The orbit of Pluto is chaotic and unpredictable. Scientists are able to predict the location of Pluto along its orbit path for the next 10-20 million years – beyond that it is unknown.",
    "Pluto is 33% water in the form of ice and 67% rock. It means that there is more than three times as much water on Pluto as in all the oceans on earth, despite the dwarf planet being just 13.05billion kgs in mass.",
    "Saturn’s moon called Titan and Jupiter’s moon called Ganymede are both larger than planet Mercury.",
    "Shooting stars are space debris that burn up when they enter Earth’s atmosphere.",
    "As of 2021, more than 600 people have been in space.",
    "It takes about five hours for sunlight to reach Pluto. It takes about eight minutes to reach Earth.",
    "Scientists speculate that the smooth appearance of Mercury’s northern plains may be due to volcanic activity. The part could have been covered with dried lava, smoothing it out as it flows, although there is no sign of volcanic activity on the surface of Mercury today.",
    "The last time human beings stepped on the moon was 1972.",
    "One Mercury day is equivalent to 59 Earth days.",
    "Mercury is not characterized by any seasons because its axis has the smallest tilt compared to other planets in the solar system.",
    "Humans knew Planet Mercury since the last 5,000 years. Sumerians linked the planet with their god of writing known as Nabu.",
    "The sun rays hitting mercury are seven times stronger than the sun rays hitting Earth.",
    "When the Earth occurs between the sun and the moon, it’s called a lunar eclipse.",
    "Before Mercury became the smallest planet, Pluto used to carry the tag. However, Pluto was scratched out of the list of the planets in the solar system.",
    "The age of the oldest rock collected on the moon is estimated to be 4.5 billion years old.",
    "Some planets have no surface to land on",
    " It would take 9.5 years to walk to the moon",
    "The moon’s deepest craters are about 4,500 meters.",
    "The moon’s surface consists of a large number of impact craters from asteroids and comets that have been colliding with the surface for many years. Since the moon doesn’t have an atmosphere or weather, these craters have been well preserved.",
    "The moon is typically extremely hot during the day and cold during the night, with average surface temperatures of 107 degrees Celsius in the day and -153 degrees Celsius during the night.",
    "The tallest mountain on the moon is Mons Huygens. It’s estimated to be 4, 700 meters tall, slightly half the height of Mount Everest, which stands at 8848 meters.",
    "The moon takes 27.3 days to revolve once. The moon also takes the same number of days to orbit Earth once, which explains why we only see one side of the moon.",
    "According to theory, the moon was formed when a rock, the same size as Mars, rammed into Earth, just before the onset of the formation of the solar system, approximately 4.5 billion years ago.",
    "The Sun’s mass takes up 99.86% of the solar system.",
    "Mars was once dominated by oceans, until they suddenly disappeared. However, all the waters could make only 1.5% of all water present on Earth.",
    "The red planet’s atmosphere is 61 times thinner than the Earth’s atmosphere.",
    "Temperature of outer space is close to absolute zero",
    "The universe is constantly expanding.",
    "The universe is made up of roughly 68% dark energy, 27% dark matter, and 5% normal matter",
    "It would take 450 million years for a modern spacecraft to reach the center of our galaxy.",
    "There is a volcano on Mars three times the size of Everest.",
    "One million Earths could fit inside the Sun – and the Sun is considered an average-size star.",
    "For years it was believed that Earth was the only planet in our solar system with liquid water. More recently, NASA revealed its strongest evidence yet that there is intermittent running water on Mars, too!",
    "Comets are leftovers from the creation of our solar system about 4.5 billion years ago – they consist of sand, ice and carbon dioxide.",
    "You wouldn’t be able to walk on Jupiter, Saturn, Uranus or Neptune because they have no solid surface!",
    "If you could fly a plane to Pluto, the trip would take more than 800 years!",
    "An asteroid about the size of a car enters Earth’s atmosphere roughly once a year – but it burns up before it reaches us. Phew!",
    "The highest mountain known to man is on an asteroid called Vesta. Measuring a whopping 22km in height, it is three times as tall as Mount Everest!",
    "There are more stars in the universe than grains of sand on all the beaches on Earth. That’s at least a billion trillion!",
    "Mercury & Venus are the only 2 planets in our solar system that have no moons.",
    "If a star passes too close to a black hole, it can be torn apart.",
    "The hottest planet in our solar system is Venus.",
    " The Milky Way is approximated to be 100,000 light-years in diameter, and is composed of 400 billion stars, which include the sun.",
    "The earth consists of an ozone layer that shields it from the dangerous solar radiation.",
    "Our solar system is 4.57 billion years old.",
    "The earth’s atmosphere is made up of nitrogen (78%), oxygen (21%) and trace quantities of other gasses, including carbon dioxide and argon.",
    "The solar system takes approximately 240 million years to complete one orbit of the galaxy.",
    "Earth is the only planet where water can occur in its 3 states; solid, liquid and vapor.",
    "Mercury rotates very slowly but it revolves around the Sun in less than 88 days. Because of this, a day in the planet is twice as long as its year.",
    "Enceladus, one of Saturn’s smaller moons, reflects 90% of the Sun’s light.",
    "The highest mountain discovered is the Olympus Mons, which is located on Mars.",
    "The Whirlpool Galaxy (M51) was the first celestial object identified as being spiral.",
    "A light-year is the distance covered by light in a single year.",
    "The Milky Way galaxy is 105,700 light-years wide.",
    "The Sun weighs about 330,000 times more than Earth.",
    "Footprints left on the Moon won’t disappear as there is no wind.",
    "Because of lower gravity, a person who weighs 100kg on Earth would weigh 40kg on Mars.",
    "There are 79 known moons orbiting Jupiter.",
    "The Martian day is 24 hours 39 minutes and 35 seconds long",
    "NASA’s Crater Observation and Sensing Satellite (LCROSS) found evidence of water on the Earth’s Moon.",
    "The Sun makes a full rotation once every 25 – 35 days.",
    "Earth is the only planet not named after a God.",
    "Due to the Sun and Moon’s gravitational pull, we have tides.",
    "Pluto is smaller than the United States.",
    "According to mathematics, white holes are possible, although as of yet we have found none.",
    "There are more volcanoes on Venus than any other planet in our solar system.",
    "Uranus’ blue glow is due to the gases in its atmosphere.",
    "In our solar system that are 4 planets known as gas giants: Jupiter, Saturn, Uranus & Neptune",
    "Uranus has 27 moons that have been discovered so far.",
    "Because of its unique tilt, a season on Uranus is equivalent to 21 Earth years.",
    "Neptune’s moon, Triton, orbits the planet backwards.",
    "There are more stars in space than there are grains of sand in the world.",
    "Neptune takes nearly 165 Earth years to make one orbit of the Sun.",
    "Pluto’s largest moon, Charon, is half the size of Pluto.",
    "The International Space Station is the largest manned object ever sent into space.",
    "A day on Pluto is lasts for 153.6 hours long.",
    "Saturn is the second largest planet in our solar system.",
    "Any free-moving liquid in outer space will form itself into a sphere.",
    "Mercury, Venus, Earth & Mars are known as the “Inner Planets”.",
    "We know more about Mars and our Moon than we do about our oceans.",
    "Only 5% of the universe is visible from Earth.",
    "Light travels from the Sun to the Earth in less than 10 minutes",
    "At any given moment, there are at least 2,000 thunderstorms happening on Earth.",
    "The Earth’s rotation is slowing slightly as time goes on",
    "If you were driving at 75 miles per hour, it would take 258 days to drive around Saturn’s rings",
    "Outer Space is only 100km away.",
    "The International Space Station circles Earth every 92 minutes.",
    "Stars twinkle because of the way light is disrupted as it passes through Earth’s atmosphere.",
    "We always see the same side of the Moon, no matter where we stand on Earth.",
    "There are three main types of galaxies: elliptical, spiral & irregular.",
    "There are approximately 100 thousand million stars in the Milky Way.",
    "Using the naked eye, you can see 3 – 7 different galaxies from Earth.",
    "In 2016, scientists detected a radio signal from a source 5 billion light-years away.",
    "The closest galaxy to us is the Andromeda Galaxy – it’s estimated at 2.5 million light-years away.",
    "The first Supernovae observed outside of our own galaxy was in 1885.",
    "The first-ever black hole photographed is 3 million times the size of Earth.",
    "The distance between the Sun & Earth is defined as an Astronomical Unit.",
    "On Venus, it snows metal and rains sulfuric acid.",
    "The Mariner 10 was the first spacecraft that visited Mercury in 1974.",
    "Space is completely silent.",
    "The Kuiper Belt is a region of the Solar System beyond the orbit of Neptune.",
    "The Hubble Space Telescope is one of the most productive scientific instruments ever built",
    "Exoplanets are planets that orbit around other stars.",
    "The center of the Milky Way smells like rum & tastes like raspberries.",
    "Our moon is moving away from Earth at a rate of 4 cm per year!",
    "Pluto is named after the Roman god of the underworld, not the Disney Dog.",
    "Spacesuit helmets have a Velcro patch, to help astronauts itch.",
    "The ISS is visible to more than 90% of the Earth’s population.",
    "Saturn is the only planet that could float in water.",
    "Asteroids are the byproducts of formations in the solar system, more than 4 billion years ago.",
    "Astronauts can’t burp in space.",
    "Uranus was originally called “George’s Star”.",
    "A sunset on Mars is blue.",
    "The Earth weighs about 81 times more than the Moon.",
    "The word “astronaut” means “star sailor” in its origins.",
    "Mercury has no atmosphere, which means there is no wind or weather.",
    "Red Dwarf stars that are low in mass can burn continually for up to 10 trillion years!",
    "Scientists once believed that the same side of Mercury always faced the Sun.",
    "Jupiter’s Red Spot is shrinking.",
    "A large percentage of asteroids are pulled in by Jupiter’s gravity.",
    "A day on Mercury is equivalent to 58 Earth days",
    "On average it takes the light only 1.3 seconds to travel from the Moon to Earth.",
    "There are 88 recognized star constellations in our night sky",
    "The center of a comet is called a “nucleus”.",
    "The Sun is white, not yellow.",
    "Scientists that study space are called astronomers.",
    "You become taller in Space because of microgravity.",
    "Ceres is the largest asteroid in Space.",
    "The ring of Saturn planet is not in the solid state.",
    "Mars has the largest dust storms, it lasts for months and covers up the whole planet.",
    "As early as 240BC the Chinese began to document the appearance of Halley’s Comet.",
    "There are 5 Dwarf Planets recognized in our Solar System.",
    "Mars is the most likely planet in our solar system to be hospitable to life.",
    "Halley’s Comet will pass over Earth again on July 26, 2061.",
    "VY CanisMajoris is the biggest star in the universe.",
    "There is a planet half the radius of the Earth with a surface made up of diamonds."
)